### ISSUE TITLE
Please update src to 1.3.9

### ISSUE THREAD

**Issue by REALMWTH** [AlexIIL/BetterLoadingScreen_1.7#2]
Hi!
I compiled non-edited src and got an error.
At loading start there's a message 'betterloadingscreen.state.minecraft_init' instead of Minecraft Initializing. It happens at 1.3.8 compiled version.
And please, update src to 1.3.9.
This mod is awesome! Thanks for the work.

**Comment by AlexIIL** [comment]
Sorry about that. It looks like I hadn't pushed my latest work/tests when I last updated this :/

**Comment by REALMWTH** [comment]
Thank you so much! You are the best :)
